src/Entity/Property.php
<?php

namespace App\Entity;

use DateTime;
use Doctrine\ORM\Mapping as ORM;
use Cocur\Slugify\Slugify;
/**
 * @ORM\Entity(repositoryClass="App\Repository\PropertyRepository")
 */
class Property
{
     const HEAT = [
        0 => "gaz",
        1 => "electric"

    ];
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;
    /**
     * @ORM\Column(type="integer")
     */
    private $surface;
    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $descripition;

    /**
     * @ORM\Column(type="integer")
     */
    private $rooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $bedrooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $floor;

    /**
     * @ORM\Column(type="integer")
     */
    private $prix;

    /**
     * @ORM\Column(type="integer")
     */
    private $heat;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adress;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $postal_code;

    /**
     * @ORM\Column(type="boolean",options={"default":false} )
     */
    private $sold;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;


    public function __construct()
    {
        $this->created_at = new DateTime('now');
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescripition(): ?string
    {
        return $this->descripition;
    }

    public function setDescripition(?string $descripition): self
    {
        $this->descripition = $descripition;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    public function getBedrooms(): ?int
    {
        return $this->bedrooms;
    }

    public function setBedrooms(int $bedrooms): self
    {
        $this->bedrooms = $bedrooms;

        return $this;
    }

    public function getFloor(): ?int
    {
        return $this->floor;
    }

    public function setFloor(int $floor): self
    {
        $this->floor = $floor;

        return $this;
    }

    public function getPrix(): ?int
    {
        return $this->prix;
    }

    public function setPrix(int $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    public function getHeat(): ?int
    {
        return $this->heat;
    }

    public function setHeat(int $heat): self
    {
        $this->heat = $heat;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getAdress(): ?string
    {
        return $this->adress;
    }

    public function setAdress(string $adress): self
    {
        $this->adress = $adress;

        return $this;
    }
    public function getSlug()
    {
        $slugify = new Slugify();
        return $slugify->slugify($this->title);
    }

    public function getPostalCode(): ?string
    {
        return $this->postal_code;
    }

    public function setPostalCode(string $postal_code): self
    {
        $this->postal_code = $postal_code;

        return $this;
    }

    public function getSold(): ?bool
    {
        return $this->sold;
    }

    public function setSold(bool $sold): self
    {
        $this->sold = $sold;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * Get the value of surface
     */ 
    public function getSurface()
    {
        return $this->surface;
    }

    /**
     * Set the value of surface
     *
     * @return  self
     */ 
    public function setSurface($surface)
    {
        $this->surface = $surface;

        return $this;
    }
    /**
     * get type de chauffge
     */
    public function getHeatType() :String
    {
     $hea = $this->heat;
     return self::HEAT[$hea];

    }
}

src/Controller/HomeController.php
<?php
namespace App\Controller;

use Symfony\Component\HttpFoundation\Response;
use Twig\Environment;

class HomeController {
    
   
    private $twig;

    public function __construct( Environment $twig)
    {
        $this->twig = $twig;
    }

    public function index(): Response
    {
      return new Response($this->twig->render('pages/home.html.twig'));

    }

}

src/Controller/PropertyController.php
<?php
namespace App\Controller;


use App\Entity\Property;
use App\Repository\PropertyRepository;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;


class PropertyController extends AbstractController {
/**
 * @Route("/biens", name = "property.index")
 */
  public function index(PropertyRepository $proprepo): Response
  {

    $properties = $proprepo->findLatest();
    return $this->render("pages/property.html.twig",[
     "properties" => $properties

    ]);
  }
  /**
   * @Route("/biens/{slug}-{id}" , name= "property.show",requirements={"slug" : "[a-z0-9\-]*"})
   * 
   */
  public function show(int $id,PropertyRepository $prorepo,String $slug) :Response
  {
    $property = $prorepo->find($id);
    if($property->getSlug() !== $slug)
    return $this->redirectToRoute('property.show',[
      'id' => $property->getId(),
      'slug'=> $property->getSlug()
    ]);
     return $this->render("pages/chosedproperty.html.twig",[
       "property" => $property
     ]);
  }


}

templates/base.html.twig
<!DOCTYPE html>
<html>

<head>
  <meta charset="UTF-8">
  <title>{% block title %}Welcome to my site!{% endblock %}</title>
  {% block stylesheets %}
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  {% endblock %}
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-primary">
    <a class="navbar-brand" href="{{ path('home') }}">Mohamed agence</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{{ path('property.index') }}">Acheter <span class="sr-only">(current)</span></a>
        </li>
      </ul>

    </div>
  </nav>

  {% block body %}


  {% endblock %}
  {% block javascripts %}{% endblock %}
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
    crossorigin="anonymous"></script>
</body>

</html>

templates/pages/chosedproperty.html.twig
{% extends "base.html.twig" %}
{% block body %}
    <div class="container mt-4">
        <div class="jumbotron">
            
                    <div class="row">
                            <div class="col-md-8"></div>
                            <div class="col-md-4">
                             <h1>{{ property.title }}</h1>
                             <h2>{{ property.rooms}} pieces</h2>
                             <div class="text-primary" style="font-size:4em;font-weight:bold"></div>
                             <a href="#" class="btn btn-primary">Contactez l agence</a>
                            </div>
                    </div>
            
        </div>
    
        <p>{{property.descripition}}</p>
      <div class="row">
          <div class="col-md-8">
              
               <h2>caracteristique</h2>
              <table class="table table-striped">
                  <tr>
                      <td>Surface habitable</td>
                      <td>{{ property.surface }} m</td>
                  </tr>
                  <tr>
                      <td>Pieces</td>
                      <td>{{property.rooms }}</td>
                  </tr>
                  <tr>
                      <td>Chambres</td>
                      <td>{{ property.bedrooms }}</td>
                  </tr>
                 <tr>
                     <td>Etage</td>
                     <td>{{ property.floor }}</td>
                 </tr>
                 <tr>
                     <td>Chauffage</td>
                     <td>{{ property.heatType }}</td>
                 </tr>
                
              </table>
          </div>
          <div class="col-md-4">
              <h2>specifité</h2>
          </div>
      </div>
    </div>
{% endblock %}

templates/pages/home.html.twig
{% extends "base.html.twig" %}
{% block body %}
<div class="jumbotron text-center">
        <div class="containe">
              <h1>Agence mohamed ben kacem</h1>
              <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa facilis, perspiciatis voluptate pariatur explicabo, assumenda alias ex sed, consectetur quis doloribus labore 
                  debitis? Deleniti porro commodi officiis quae nobis excepturi.</p>
      
        </div>
      </div>

{% endblock %}

templates/pages/property.html.twig
{% extends "base.html.twig" %}
{% block body %}
<div class="container">
    <h1>les dernies biens</h1>
  <div class="row flex">
  {% for property in properties %}
      <div class="col-3">
          <div class="card">
              <div class="card-body">
                  <h5 class="card-title"> 
                    <a href="{{ path('property.show',{id: property.id, slug: property.slug}) }}">{{ property.title }}</a>
                  </h5>
                  <p class="card-text">{{ property.city}} {{ property.postalCode }}</p>
                  <div class="text-primary">{{ property.prix }}</div>
              </div>
          </div>
      </div>
  {% endfor %}

  </div>

</div>  

{% endblock %}